name: legacy_vault
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: ^3.6.0
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  dio: ^5.4.0
  fluttertoast: ^8.2.4
  sizer: ^2.0.15
  fl_chart: ^0.65.0
  google_fonts: ^6.1.0
  web: any
  # Sync and Inheritance Packages
  crypto: ^3.0.6
  encrypt: ^5.0.3
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  local_auth: ^2.3.0
  package_info_plus: ^8.3.0
  uuid: ^4.5.1
  permission_handler: ^12.0.1
  flutter_secure_storage: ^9.2.4
  flutter_blue_plus: ^1.35.5
  nearby_connections: ^4.3.0
  web_socket_channel: ^3.0.3
  synchronized: ^3.4.0
  drift: ^2.28.0
  json_annotation: ^4.9.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.10.0
  build_runner: ^2.6.0
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/